name: Android Fastlane Firebase App Distribution

on :
  push:
    branches:
      - main
jobs:
 distribution_to_Firebase:

   runs-on: ubuntu-latest

   steps:
     - name: Checkout my repo code
       uses: actions/checkout@v2

     - name: Set up JDK 17
       uses: actions/setup-java@v2
       with:
         java-version: '17'
         distribution: 'temurin'

     - name: Set up Flutter
       uses: subosito/flutter-action@v2
       with:
         channel: 'stable'

     - name: Set up Ruby
       uses: ruby/setup-ruby@v1
       with:
         ruby-version: '3.3'
         bundler-cache: true
         working-directory: android    

     - name: Build and Distribute App

       env:
         FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
         FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
         

       run: |
         bundle exec fastlane android firebase_distribution
       working-directory: android/fastlane