default_platform(:android)
platform :android do
  desc "Lane for Android Firebase App Distribution (build done separately)"
  lane :firebase_distribution_simple do
    firebase_app_distribution(
        app: ENV["FIREBASE_APP_ID"],
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "zyadm2137@gmail.com",
        release_notes: "Testing something with fastlane, add secure environment variables",
    )
  end
end